server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    # postgresql
    url: jdbc:postgresql://localhost:5432/studentDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
